# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgn <- function(x) {
    .Call('_conquer2_sgn', PACKAGE = 'conquer2', x)
}

mad <- function(x) {
    .Call('_conquer2_mad', PACKAGE = 'conquer2', x)
}

standardize <- function(X, mx, sx1, p) {
    .Call('_conquer2_standardize', PACKAGE = 'conquer2', X, mx, sx1, p)
}

softThresh <- function(x, Lambda, p) {
    .Call('_conquer2_softThresh', PACKAGE = 'conquer2', x, Lambda, p)
}

lossQr <- function(Z, Y, beta, tau, i, dev, devsq) {
    invisible(.Call('_conquer2_lossQr', PACKAGE = 'conquer2', Z, Y, beta, tau, i, dev, devsq))
}

cmptLambdaLasso <- function(lambda, p) {
    .Call('_conquer2_cmptLambdaLasso', PACKAGE = 'conquer2', lambda, p)
}

lossL2 <- function(Z, Y, beta, n1, tau) {
    .Call('_conquer2_lossL2', PACKAGE = 'conquer2', Z, Y, beta, n1, tau)
}

updateL2 <- function(Z, Y, beta, grad, n1, tau) {
    .Call('_conquer2_updateL2', PACKAGE = 'conquer2', Z, Y, beta, grad, n1, tau)
}

lammL2 <- function(Z, Y, Lambda, beta, tau, phi, gamma, p, n1) {
    .Call('_conquer2_lammL2', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, phi, gamma, p, n1)
}

lasso <- function(Z, Y, lambda, tau, p, n1, phi0, gamma, epsilon, iteMax) {
    .Call('_conquer2_lasso', PACKAGE = 'conquer2', Z, Y, lambda, tau, p, n1, phi0, gamma, epsilon, iteMax)
}

cmptLambdaSCAD <- function(beta, lambda, p, para) {
    .Call('_conquer2_cmptLambdaSCAD', PACKAGE = 'conquer2', beta, lambda, p, para)
}

cmptLambdaMCP <- function(beta, lambda, p, para) {
    .Call('_conquer2_cmptLambdaMCP', PACKAGE = 'conquer2', beta, lambda, p, para)
}

lossGaussHd <- function(Z, Y, beta, tau, h, h1, h2) {
    .Call('_conquer2_lossGaussHd', PACKAGE = 'conquer2', Z, Y, beta, tau, h, h1, h2)
}

updateGaussHd <- function(Z, Y, beta, grad, tau, n1, h, h1, h2) {
    .Call('_conquer2_updateGaussHd', PACKAGE = 'conquer2', Z, Y, beta, grad, tau, n1, h, h1, h2)
}

lammGaussLasso <- function(Z, Y, Lambda, beta, tau, phi, gamma, p, h, n1, h1, h2) {
    .Call('_conquer2_lammGaussLasso', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, phi, gamma, p, h, n1, h1, h2)
}

lammGaussElastic <- function(Z, Y, Lambda, beta, tau, alpha, phi, gamma, p, h, n1, h1, h2) {
    .Call('_conquer2_lammGaussElastic', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, alpha, phi, gamma, p, h, n1, h1, h2)
}

gaussLasso <- function(Z, Y, lambda, tau, p, n1, h, h1, h2, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_gaussLasso', PACKAGE = 'conquer2', Z, Y, lambda, tau, p, n1, h, h1, h2, phi0, gamma, epsilon, iteMax)
}

gaussLassoWarm <- function(Z, Y, lambda, betaWarm, tau, p, n1, h, h1, h2, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_gaussLassoWarm', PACKAGE = 'conquer2', Z, Y, lambda, betaWarm, tau, p, n1, h, h1, h2, phi0, gamma, epsilon, iteMax)
}

gaussElastic <- function(Z, Y, lambda, tau, alpha, p, n1, h, h1, h2, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_gaussElastic', PACKAGE = 'conquer2', Z, Y, lambda, tau, alpha, p, n1, h, h1, h2, phi0, gamma, epsilon, iteMax)
}

gaussElasticWarm <- function(Z, Y, lambda, betaWarm, tau, alpha, p, n1, h, h1, h2, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_gaussElasticWarm', PACKAGE = 'conquer2', Z, Y, lambda, betaWarm, tau, alpha, p, n1, h, h1, h2, phi0, gamma, epsilon, iteMax)
}

conquerGaussLasso <- function(X, Y, lambda, tau, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerGaussLasso', PACKAGE = 'conquer2', X, Y, lambda, tau, h, phi0, gamma, epsilon, iteMax)
}

conquerGaussLassoSeq <- function(X, Y, lambdaSeq, tau, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerGaussLassoSeq', PACKAGE = 'conquer2', X, Y, lambdaSeq, tau, h, phi0, gamma, epsilon, iteMax)
}

conquerGaussElastic <- function(X, Y, lambda, tau, alpha, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerGaussElastic', PACKAGE = 'conquer2', X, Y, lambda, tau, alpha, h, phi0, gamma, epsilon, iteMax)
}

conquerGaussElasticSeq <- function(X, Y, lambdaSeq, tau, alpha, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerGaussElasticSeq', PACKAGE = 'conquer2', X, Y, lambdaSeq, tau, alpha, h, phi0, gamma, epsilon, iteMax)
}

lossLogisticHd <- function(Z, Y, beta, tau, h, h1) {
    .Call('_conquer2_lossLogisticHd', PACKAGE = 'conquer2', Z, Y, beta, tau, h, h1)
}

updateLogisticHd <- function(Z, Y, beta, grad, tau, n1, h, h1) {
    .Call('_conquer2_updateLogisticHd', PACKAGE = 'conquer2', Z, Y, beta, grad, tau, n1, h, h1)
}

lammLogisticLasso <- function(Z, Y, Lambda, beta, tau, phi, gamma, p, h, n1, h1) {
    .Call('_conquer2_lammLogisticLasso', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, phi, gamma, p, h, n1, h1)
}

lammLogisticElastic <- function(Z, Y, Lambda, beta, tau, alpha, phi, gamma, p, h, n1, h1) {
    .Call('_conquer2_lammLogisticElastic', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, alpha, phi, gamma, p, h, n1, h1)
}

logisticLasso <- function(Z, Y, lambda, tau, p, n1, h, h1, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_logisticLasso', PACKAGE = 'conquer2', Z, Y, lambda, tau, p, n1, h, h1, phi0, gamma, epsilon, iteMax)
}

logisticLassoWarm <- function(Z, Y, lambda, betaWarm, tau, p, n1, h, h1, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_logisticLassoWarm', PACKAGE = 'conquer2', Z, Y, lambda, betaWarm, tau, p, n1, h, h1, phi0, gamma, epsilon, iteMax)
}

logisticElastic <- function(Z, Y, lambda, tau, alpha, p, n1, h, h1, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_logisticElastic', PACKAGE = 'conquer2', Z, Y, lambda, tau, alpha, p, n1, h, h1, phi0, gamma, epsilon, iteMax)
}

logisticElasticWarm <- function(Z, Y, lambda, betaWarm, tau, alpha, p, n1, h, h1, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_logisticElasticWarm', PACKAGE = 'conquer2', Z, Y, lambda, betaWarm, tau, alpha, p, n1, h, h1, phi0, gamma, epsilon, iteMax)
}

conquerLogisticLasso <- function(X, Y, lambda, tau, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerLogisticLasso', PACKAGE = 'conquer2', X, Y, lambda, tau, h, phi0, gamma, epsilon, iteMax)
}

conquerLogisticLassoSeq <- function(X, Y, lambdaSeq, tau, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerLogisticLassoSeq', PACKAGE = 'conquer2', X, Y, lambdaSeq, tau, h, phi0, gamma, epsilon, iteMax)
}

conquerLogisticElastic <- function(X, Y, lambda, tau, alpha, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerLogisticElastic', PACKAGE = 'conquer2', X, Y, lambda, tau, alpha, h, phi0, gamma, epsilon, iteMax)
}

conquerLogisticElasticSeq <- function(X, Y, lambdaSeq, tau, alpha, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerLogisticElasticSeq', PACKAGE = 'conquer2', X, Y, lambdaSeq, tau, alpha, h, phi0, gamma, epsilon, iteMax)
}

lossParaHd <- function(Z, Y, beta, tau, h, h1, h3) {
    .Call('_conquer2_lossParaHd', PACKAGE = 'conquer2', Z, Y, beta, tau, h, h1, h3)
}

updateParaHd <- function(Z, Y, beta, grad, tau, n1, h, h1, h3) {
    .Call('_conquer2_updateParaHd', PACKAGE = 'conquer2', Z, Y, beta, grad, tau, n1, h, h1, h3)
}

lammParaLasso <- function(Z, Y, Lambda, beta, tau, phi, gamma, p, h, n1, h1, h3) {
    .Call('_conquer2_lammParaLasso', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, phi, gamma, p, h, n1, h1, h3)
}

lammParaElastic <- function(Z, Y, Lambda, beta, tau, alpha, phi, gamma, p, h, n1, h1, h3) {
    .Call('_conquer2_lammParaElastic', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, alpha, phi, gamma, p, h, n1, h1, h3)
}

paraLasso <- function(Z, Y, lambda, tau, p, n1, h, h1, h3, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_paraLasso', PACKAGE = 'conquer2', Z, Y, lambda, tau, p, n1, h, h1, h3, phi0, gamma, epsilon, iteMax)
}

paraLassoWarm <- function(Z, Y, lambda, betaWarm, tau, p, n1, h, h1, h3, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_paraLassoWarm', PACKAGE = 'conquer2', Z, Y, lambda, betaWarm, tau, p, n1, h, h1, h3, phi0, gamma, epsilon, iteMax)
}

paraElastic <- function(Z, Y, lambda, tau, alpha, p, n1, h, h1, h3, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_paraElastic', PACKAGE = 'conquer2', Z, Y, lambda, tau, alpha, p, n1, h, h1, h3, phi0, gamma, epsilon, iteMax)
}

paraElasticWarm <- function(Z, Y, lambda, betaWarm, tau, alpha, p, n1, h, h1, h3, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_paraElasticWarm', PACKAGE = 'conquer2', Z, Y, lambda, betaWarm, tau, alpha, p, n1, h, h1, h3, phi0, gamma, epsilon, iteMax)
}

conquerParaLasso <- function(X, Y, lambda, tau, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerParaLasso', PACKAGE = 'conquer2', X, Y, lambda, tau, h, phi0, gamma, epsilon, iteMax)
}

conquerParaLassoSeq <- function(X, Y, lambdaSeq, tau, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerParaLassoSeq', PACKAGE = 'conquer2', X, Y, lambdaSeq, tau, h, phi0, gamma, epsilon, iteMax)
}

conquerParaElastic <- function(X, Y, lambda, tau, alpha, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerParaElastic', PACKAGE = 'conquer2', X, Y, lambda, tau, alpha, h, phi0, gamma, epsilon, iteMax)
}

conquerParaElasticSeq <- function(X, Y, lambdaSeq, tau, alpha, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerParaElasticSeq', PACKAGE = 'conquer2', X, Y, lambdaSeq, tau, alpha, h, phi0, gamma, epsilon, iteMax)
}

lossTrianHd <- function(Z, Y, beta, tau, h, h1, h2) {
    .Call('_conquer2_lossTrianHd', PACKAGE = 'conquer2', Z, Y, beta, tau, h, h1, h2)
}

updateTrianHd <- function(Z, Y, beta, grad, tau, n1, h, h1, h2) {
    .Call('_conquer2_updateTrianHd', PACKAGE = 'conquer2', Z, Y, beta, grad, tau, n1, h, h1, h2)
}

lammTrianLasso <- function(Z, Y, Lambda, beta, tau, phi, gamma, p, h, n1, h1, h2) {
    .Call('_conquer2_lammTrianLasso', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, phi, gamma, p, h, n1, h1, h2)
}

lammTrianElastic <- function(Z, Y, Lambda, beta, tau, alpha, phi, gamma, p, h, n1, h1, h2) {
    .Call('_conquer2_lammTrianElastic', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, alpha, phi, gamma, p, h, n1, h1, h2)
}

trianLasso <- function(Z, Y, lambda, tau, p, n1, h, h1, h2, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_trianLasso', PACKAGE = 'conquer2', Z, Y, lambda, tau, p, n1, h, h1, h2, phi0, gamma, epsilon, iteMax)
}

trianLassoWarm <- function(Z, Y, lambda, betaWarm, tau, p, n1, h, h1, h2, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_trianLassoWarm', PACKAGE = 'conquer2', Z, Y, lambda, betaWarm, tau, p, n1, h, h1, h2, phi0, gamma, epsilon, iteMax)
}

trianElastic <- function(Z, Y, lambda, tau, alpha, p, n1, h, h1, h2, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_trianElastic', PACKAGE = 'conquer2', Z, Y, lambda, tau, alpha, p, n1, h, h1, h2, phi0, gamma, epsilon, iteMax)
}

trianElasticWarm <- function(Z, Y, lambda, betaWarm, tau, alpha, p, n1, h, h1, h2, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_trianElasticWarm', PACKAGE = 'conquer2', Z, Y, lambda, betaWarm, tau, alpha, p, n1, h, h1, h2, phi0, gamma, epsilon, iteMax)
}

conquerTrianLasso <- function(X, Y, lambda, tau, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerTrianLasso', PACKAGE = 'conquer2', X, Y, lambda, tau, h, phi0, gamma, epsilon, iteMax)
}

conquerTrianLassoSeq <- function(X, Y, lambdaSeq, tau, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerTrianLassoSeq', PACKAGE = 'conquer2', X, Y, lambdaSeq, tau, h, phi0, gamma, epsilon, iteMax)
}

conquerTrianElastic <- function(X, Y, lambda, tau, alpha, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerTrianElastic', PACKAGE = 'conquer2', X, Y, lambda, tau, alpha, h, phi0, gamma, epsilon, iteMax)
}

conquerTrianElasticSeq <- function(X, Y, lambdaSeq, tau, alpha, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerTrianElasticSeq', PACKAGE = 'conquer2', X, Y, lambdaSeq, tau, alpha, h, phi0, gamma, epsilon, iteMax)
}

lossUnifHd <- function(Z, Y, beta, tau, h, h1) {
    .Call('_conquer2_lossUnifHd', PACKAGE = 'conquer2', Z, Y, beta, tau, h, h1)
}

updateUnifHd <- function(Z, Y, beta, grad, tau, n1, h, h1) {
    .Call('_conquer2_updateUnifHd', PACKAGE = 'conquer2', Z, Y, beta, grad, tau, n1, h, h1)
}

lammUnifLasso <- function(Z, Y, Lambda, beta, tau, phi, gamma, p, h, n1, h1) {
    .Call('_conquer2_lammUnifLasso', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, phi, gamma, p, h, n1, h1)
}

lammUnifElastic <- function(Z, Y, Lambda, beta, tau, alpha, phi, gamma, p, h, n1, h1) {
    .Call('_conquer2_lammUnifElastic', PACKAGE = 'conquer2', Z, Y, Lambda, beta, tau, alpha, phi, gamma, p, h, n1, h1)
}

unifLasso <- function(Z, Y, lambda, tau, p, n1, h, h1, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_unifLasso', PACKAGE = 'conquer2', Z, Y, lambda, tau, p, n1, h, h1, phi0, gamma, epsilon, iteMax)
}

unifLassoWarm <- function(Z, Y, lambda, betaWarm, tau, p, n1, h, h1, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_unifLassoWarm', PACKAGE = 'conquer2', Z, Y, lambda, betaWarm, tau, p, n1, h, h1, phi0, gamma, epsilon, iteMax)
}

unifElastic <- function(Z, Y, lambda, tau, alpha, p, n1, h, h1, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_unifElastic', PACKAGE = 'conquer2', Z, Y, lambda, tau, alpha, p, n1, h, h1, phi0, gamma, epsilon, iteMax)
}

unifElasticWarm <- function(Z, Y, lambda, betaWarm, tau, alpha, p, n1, h, h1, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_unifElasticWarm', PACKAGE = 'conquer2', Z, Y, lambda, betaWarm, tau, alpha, p, n1, h, h1, phi0, gamma, epsilon, iteMax)
}

conquerUnifLasso <- function(X, Y, lambda, tau, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerUnifLasso', PACKAGE = 'conquer2', X, Y, lambda, tau, h, phi0, gamma, epsilon, iteMax)
}

conquerUnifLassoSeq <- function(X, Y, lambdaSeq, tau, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerUnifLassoSeq', PACKAGE = 'conquer2', X, Y, lambdaSeq, tau, h, phi0, gamma, epsilon, iteMax)
}

conquerUnifElastic <- function(X, Y, lambda, tau, alpha, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerUnifElastic', PACKAGE = 'conquer2', X, Y, lambda, tau, alpha, h, phi0, gamma, epsilon, iteMax)
}

conquerUnifElasticSeq <- function(X, Y, lambdaSeq, tau, alpha, h, phi0 = 0.01, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_conquer2_conquerUnifElasticSeq', PACKAGE = 'conquer2', X, Y, lambdaSeq, tau, alpha, h, phi0, gamma, epsilon, iteMax)
}

updateHuber <- function(Z, res, tau, der, grad, n, rob, n1) {
    invisible(.Call('_conquer2_updateHuber', PACKAGE = 'conquer2', Z, res, tau, der, grad, n, rob, n1))
}

updateGauss <- function(Z, res, der, grad, tau, n1, h1) {
    invisible(.Call('_conquer2_updateGauss', PACKAGE = 'conquer2', Z, res, der, grad, tau, n1, h1))
}

updateLogistic <- function(Z, res, der, grad, tau, n1, h1) {
    invisible(.Call('_conquer2_updateLogistic', PACKAGE = 'conquer2', Z, res, der, grad, tau, n1, h1))
}

updateUnif <- function(Z, res, der, grad, n, tau, h, n1, h1) {
    invisible(.Call('_conquer2_updateUnif', PACKAGE = 'conquer2', Z, res, der, grad, n, tau, h, n1, h1))
}

updatePara <- function(Z, res, der, grad, n, tau, h, n1, h1, h3) {
    invisible(.Call('_conquer2_updatePara', PACKAGE = 'conquer2', Z, res, der, grad, n, tau, h, n1, h1, h3))
}

updateTrian <- function(Z, res, der, grad, n, tau, h, n1, h1, h2) {
    invisible(.Call('_conquer2_updateTrian', PACKAGE = 'conquer2', Z, res, der, grad, n, tau, h, n1, h1, h2))
}

huberReg <- function(Z, Y, tau, der, gradOld, gradNew, n, p, n1, tol = 0.0001, constTau = 1.345, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_huberReg', PACKAGE = 'conquer2', Z, Y, tau, der, gradOld, gradNew, n, p, n1, tol, constTau, iteMax, stepMax)
}

smqrGauss <- function(X, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrGauss', PACKAGE = 'conquer2', X, Y, tau, h, constTau, tol, iteMax, stepMax)
}

smqrGaussNsd <- function(Z, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrGaussNsd', PACKAGE = 'conquer2', Z, Y, tau, h, constTau, tol, iteMax, stepMax)
}

smqrGaussIni <- function(X, Y, betaHat, p, tau = 0.5, h = 0.05, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrGaussIni', PACKAGE = 'conquer2', X, Y, betaHat, p, tau, h, tol, iteMax, stepMax)
}

smqrLogistic <- function(X, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrLogistic', PACKAGE = 'conquer2', X, Y, tau, h, constTau, tol, iteMax, stepMax)
}

smqrLogisticNsd <- function(Z, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrLogisticNsd', PACKAGE = 'conquer2', Z, Y, tau, h, constTau, tol, iteMax, stepMax)
}

smqrLogisticIni <- function(X, Y, betaHat, p, tau = 0.5, h = 0.05, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrLogisticIni', PACKAGE = 'conquer2', X, Y, betaHat, p, tau, h, tol, iteMax, stepMax)
}

smqrUnif <- function(X, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrUnif', PACKAGE = 'conquer2', X, Y, tau, h, constTau, tol, iteMax, stepMax)
}

smqrUnifNsd <- function(Z, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrUnifNsd', PACKAGE = 'conquer2', Z, Y, tau, h, constTau, tol, iteMax, stepMax)
}

smqrUnifIni <- function(X, Y, betaHat, p, tau = 0.5, h = 0.05, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrUnifIni', PACKAGE = 'conquer2', X, Y, betaHat, p, tau, h, tol, iteMax, stepMax)
}

smqrPara <- function(X, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrPara', PACKAGE = 'conquer2', X, Y, tau, h, constTau, tol, iteMax, stepMax)
}

smqrParaNsd <- function(Z, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrParaNsd', PACKAGE = 'conquer2', Z, Y, tau, h, constTau, tol, iteMax, stepMax)
}

smqrParaIni <- function(X, Y, betaHat, p, tau = 0.5, h = 0.05, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrParaIni', PACKAGE = 'conquer2', X, Y, betaHat, p, tau, h, tol, iteMax, stepMax)
}

smqrTrian <- function(X, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrTrian', PACKAGE = 'conquer2', X, Y, tau, h, constTau, tol, iteMax, stepMax)
}

smqrTrianNsd <- function(Z, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrTrianNsd', PACKAGE = 'conquer2', Z, Y, tau, h, constTau, tol, iteMax, stepMax)
}

smqrTrianIni <- function(X, Y, betaHat, p, tau = 0.5, h = 0.05, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrTrianIni', PACKAGE = 'conquer2', X, Y, betaHat, p, tau, h, tol, iteMax, stepMax)
}

smqrGaussProc <- function(X, Y, tauSeq, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrGaussProc', PACKAGE = 'conquer2', X, Y, tauSeq, h, constTau, tol, iteMax, stepMax)
}

smqrLogisticProc <- function(X, Y, tauSeq, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrLogisticProc', PACKAGE = 'conquer2', X, Y, tauSeq, h, constTau, tol, iteMax, stepMax)
}

smqrUnifProc <- function(X, Y, tauSeq, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrUnifProc', PACKAGE = 'conquer2', X, Y, tauSeq, h, constTau, tol, iteMax, stepMax)
}

smqrParaProc <- function(X, Y, tauSeq, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrParaProc', PACKAGE = 'conquer2', X, Y, tauSeq, h, constTau, tol, iteMax, stepMax)
}

smqrTrianProc <- function(X, Y, tauSeq, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrTrianProc', PACKAGE = 'conquer2', X, Y, tauSeq, h, constTau, tol, iteMax, stepMax)
}

smqrGaussInf <- function(X, Y, betaHat, n, p, h = 0.05, tau = 0.5, B = 1000L, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrGaussInf', PACKAGE = 'conquer2', X, Y, betaHat, n, p, h, tau, B, tol, iteMax, stepMax)
}

smqrLogisticInf <- function(X, Y, betaHat, n, p, h = 0.05, tau = 0.5, B = 1000L, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrLogisticInf', PACKAGE = 'conquer2', X, Y, betaHat, n, p, h, tau, B, tol, iteMax, stepMax)
}

smqrUnifInf <- function(X, Y, betaHat, n, p, h = 0.05, tau = 0.5, B = 1000L, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrUnifInf', PACKAGE = 'conquer2', X, Y, betaHat, n, p, h, tau, B, tol, iteMax, stepMax)
}

smqrParaInf <- function(X, Y, betaHat, n, p, h = 0.05, tau = 0.5, B = 1000L, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrParaInf', PACKAGE = 'conquer2', X, Y, betaHat, n, p, h, tau, B, tol, iteMax, stepMax)
}

smqrTrianInf <- function(X, Y, betaHat, n, p, h = 0.05, tau = 0.5, B = 1000L, tol = 0.0001, iteMax = 5000L, stepMax = 100.0) {
    .Call('_conquer2_smqrTrianInf', PACKAGE = 'conquer2', X, Y, betaHat, n, p, h, tau, B, tol, iteMax, stepMax)
}

huberRegUbd <- function(Z, Y, tau, der, gradOld, gradNew, n, p, n1, tol = 0.0001, constTau = 1.345, iteMax = 5000L) {
    .Call('_conquer2_huberRegUbd', PACKAGE = 'conquer2', Z, Y, tau, der, gradOld, gradNew, n, p, n1, tol, constTau, iteMax)
}

smqrGaussUbd <- function(X, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrGaussUbd', PACKAGE = 'conquer2', X, Y, tau, h, constTau, tol, iteMax)
}

smqrGaussNsdUbd <- function(Z, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrGaussNsdUbd', PACKAGE = 'conquer2', Z, Y, tau, h, constTau, tol, iteMax)
}

smqrGaussIniUbd <- function(X, Y, betaHat, p, tau = 0.5, h = 0.05, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrGaussIniUbd', PACKAGE = 'conquer2', X, Y, betaHat, p, tau, h, tol, iteMax)
}

smqrLogisticUbd <- function(X, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrLogisticUbd', PACKAGE = 'conquer2', X, Y, tau, h, constTau, tol, iteMax)
}

smqrLogisticNsdUbd <- function(Z, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrLogisticNsdUbd', PACKAGE = 'conquer2', Z, Y, tau, h, constTau, tol, iteMax)
}

smqrLogisticIniUbd <- function(X, Y, betaHat, p, tau = 0.5, h = 0.05, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrLogisticIniUbd', PACKAGE = 'conquer2', X, Y, betaHat, p, tau, h, tol, iteMax)
}

smqrUnifUbd <- function(X, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrUnifUbd', PACKAGE = 'conquer2', X, Y, tau, h, constTau, tol, iteMax)
}

smqrUnifNsdUbd <- function(Z, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrUnifNsdUbd', PACKAGE = 'conquer2', Z, Y, tau, h, constTau, tol, iteMax)
}

smqrUnifIniUbd <- function(X, Y, betaHat, p, tau = 0.5, h = 0.05, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrUnifIniUbd', PACKAGE = 'conquer2', X, Y, betaHat, p, tau, h, tol, iteMax)
}

smqrParaUbd <- function(X, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrParaUbd', PACKAGE = 'conquer2', X, Y, tau, h, constTau, tol, iteMax)
}

smqrParaNsdUbd <- function(Z, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrParaNsdUbd', PACKAGE = 'conquer2', Z, Y, tau, h, constTau, tol, iteMax)
}

smqrParaIniUbd <- function(X, Y, betaHat, p, tau = 0.5, h = 0.05, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrParaIniUbd', PACKAGE = 'conquer2', X, Y, betaHat, p, tau, h, tol, iteMax)
}

smqrTrianUbd <- function(X, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrTrianUbd', PACKAGE = 'conquer2', X, Y, tau, h, constTau, tol, iteMax)
}

smqrTrianNsdUbd <- function(Z, Y, tau = 0.5, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrTrianNsdUbd', PACKAGE = 'conquer2', Z, Y, tau, h, constTau, tol, iteMax)
}

smqrTrianIniUbd <- function(X, Y, betaHat, p, tau = 0.5, h = 0.05, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrTrianIniUbd', PACKAGE = 'conquer2', X, Y, betaHat, p, tau, h, tol, iteMax)
}

smqrGaussProcUbd <- function(X, Y, tauSeq, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrGaussProcUbd', PACKAGE = 'conquer2', X, Y, tauSeq, h, constTau, tol, iteMax)
}

smqrLogisticProcUbd <- function(X, Y, tauSeq, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrLogisticProcUbd', PACKAGE = 'conquer2', X, Y, tauSeq, h, constTau, tol, iteMax)
}

smqrUnifProcUbd <- function(X, Y, tauSeq, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrUnifProcUbd', PACKAGE = 'conquer2', X, Y, tauSeq, h, constTau, tol, iteMax)
}

smqrParaProcUbd <- function(X, Y, tauSeq, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrParaProcUbd', PACKAGE = 'conquer2', X, Y, tauSeq, h, constTau, tol, iteMax)
}

smqrTrianProcUbd <- function(X, Y, tauSeq, h = 0.05, constTau = 1.345, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrTrianProcUbd', PACKAGE = 'conquer2', X, Y, tauSeq, h, constTau, tol, iteMax)
}

smqrGaussInfUbd <- function(X, Y, betaHat, n, p, h = 0.05, tau = 0.5, B = 1000L, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrGaussInfUbd', PACKAGE = 'conquer2', X, Y, betaHat, n, p, h, tau, B, tol, iteMax)
}

smqrLogisticInfUbd <- function(X, Y, betaHat, n, p, h = 0.05, tau = 0.5, B = 1000L, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrLogisticInfUbd', PACKAGE = 'conquer2', X, Y, betaHat, n, p, h, tau, B, tol, iteMax)
}

smqrUnifInfUbd <- function(X, Y, betaHat, n, p, h = 0.05, tau = 0.5, B = 1000L, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrUnifInfUbd', PACKAGE = 'conquer2', X, Y, betaHat, n, p, h, tau, B, tol, iteMax)
}

smqrParaInfUbd <- function(X, Y, betaHat, n, p, h = 0.05, tau = 0.5, B = 1000L, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrParaInfUbd', PACKAGE = 'conquer2', X, Y, betaHat, n, p, h, tau, B, tol, iteMax)
}

smqrTrianInfUbd <- function(X, Y, betaHat, n, p, h = 0.05, tau = 0.5, B = 1000L, tol = 0.0001, iteMax = 5000L) {
    .Call('_conquer2_smqrTrianInfUbd', PACKAGE = 'conquer2', X, Y, betaHat, n, p, h, tau, B, tol, iteMax)
}

asymptoticCI <- function(X, res, coeff, tau, n, h, z) {
    .Call('_conquer2_asymptoticCI', PACKAGE = 'conquer2', X, res, coeff, tau, n, h, z)
}

